kind: Deployment
apiVersion: apps/v1
metadata:
   name: sapna
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: sapna
   template:
      metadata:
        labels:
          app: sapna
      spec:
       containers:
        - name: sapna
          image: sravtar/kubernetes_deployment_pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80
